# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\dev\core\rf_maya\nuTools\util\nuPicker\ui\nuPicker.ui'
#
# Created: Fri Jan 04 14:17:37 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_nuPicker_MainWindow(object):
    def setupUi(self, nuPicker_MainWindow):
        nuPicker_MainWindow.setObjectName("nuPicker_MainWindow")
        nuPicker_MainWindow.resize(535, 642)
        self.centralwidget = QtWidgets.QWidget(nuPicker_MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.header_horizontalWidget.setObjectName("header_horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_horizontalWidget)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.namespace_label = QtWidgets.QLabel(self.header_horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.namespace_label.sizePolicy().hasHeightForWidth())
        self.namespace_label.setSizePolicy(sizePolicy)
        self.namespace_label.setObjectName("namespace_label")
        self.horizontalLayout_2.addWidget(self.namespace_label)
        self.namespace_comboBox = QtWidgets.QComboBox(self.header_horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.namespace_comboBox.sizePolicy().hasHeightForWidth())
        self.namespace_comboBox.setSizePolicy(sizePolicy)
        self.namespace_comboBox.setEditable(True)
        self.namespace_comboBox.setFrame(True)
        self.namespace_comboBox.setObjectName("namespace_comboBox")
        self.horizontalLayout_2.addWidget(self.namespace_comboBox)
        self.refresh_toolButton = QtWidgets.QToolButton(self.header_horizontalWidget)
        self.refresh_toolButton.setText("")
        self.refresh_toolButton.setObjectName("refresh_toolButton")
        self.horizontalLayout_2.addWidget(self.refresh_toolButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout_3.addWidget(self.header_horizontalWidget)
        self.main_splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_splitter.sizePolicy().hasHeightForWidth())
        self.main_splitter.setSizePolicy(sizePolicy)
        self.main_splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.tools_verticalWidget = QtWidgets.QWidget(self.main_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_verticalWidget.sizePolicy().hasHeightForWidth())
        self.tools_verticalWidget.setSizePolicy(sizePolicy)
        self.tools_verticalWidget.setMaximumSize(QtCore.QSize(65, 16777215))
        self.tools_verticalWidget.setObjectName("tools_verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tools_verticalWidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_groupBox = QtWidgets.QGroupBox(self.tools_verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_groupBox.sizePolicy().hasHeightForWidth())
        self.label_groupBox.setSizePolicy(sizePolicy)
        self.label_groupBox.setObjectName("label_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.label_groupBox)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(2, 6, 2, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_lineEdit = QtWidgets.QLineEdit(self.label_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lineEdit.sizePolicy().hasHeightForWidth())
        self.label_lineEdit.setSizePolicy(sizePolicy)
        self.label_lineEdit.setObjectName("label_lineEdit")
        self.verticalLayout.addWidget(self.label_lineEdit)
        self.verticalLayout_2.addWidget(self.label_groupBox)
        self.size_groupBox = QtWidgets.QGroupBox(self.tools_verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.size_groupBox.sizePolicy().hasHeightForWidth())
        self.size_groupBox.setSizePolicy(sizePolicy)
        self.size_groupBox.setObjectName("size_groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.size_groupBox)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setContentsMargins(3, 6, 3, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scale_label = QtWidgets.QLabel(self.size_groupBox)
        self.scale_label.setText("")
        self.scale_label.setObjectName("scale_label")
        self.verticalLayout_4.addWidget(self.scale_label)
        self.xSize_horizontalLayout = QtWidgets.QHBoxLayout()
        self.xSize_horizontalLayout.setSpacing(2)
        self.xSize_horizontalLayout.setObjectName("xSize_horizontalLayout")
        self.x_label = QtWidgets.QLabel(self.size_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_label.sizePolicy().hasHeightForWidth())
        self.x_label.setSizePolicy(sizePolicy)
        self.x_label.setObjectName("x_label")
        self.xSize_horizontalLayout.addWidget(self.x_label)
        self.sizeX_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.size_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizeX_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.sizeX_doubleSpinBox.setSizePolicy(sizePolicy)
        self.sizeX_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sizeX_doubleSpinBox.setWrapping(False)
        self.sizeX_doubleSpinBox.setFrame(True)
        self.sizeX_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sizeX_doubleSpinBox.setDecimals(1)
        self.sizeX_doubleSpinBox.setMinimum(0.1)
        self.sizeX_doubleSpinBox.setMaximum(10.0)
        self.sizeX_doubleSpinBox.setSingleStep(0.1)
        self.sizeX_doubleSpinBox.setProperty("value", 1.0)
        self.sizeX_doubleSpinBox.setObjectName("sizeX_doubleSpinBox")
        self.xSize_horizontalLayout.addWidget(self.sizeX_doubleSpinBox)
        self.verticalLayout_4.addLayout(self.xSize_horizontalLayout)
        self.ySize_horizontalLayout = QtWidgets.QHBoxLayout()
        self.ySize_horizontalLayout.setSpacing(2)
        self.ySize_horizontalLayout.setObjectName("ySize_horizontalLayout")
        self.y_label = QtWidgets.QLabel(self.size_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_label.sizePolicy().hasHeightForWidth())
        self.y_label.setSizePolicy(sizePolicy)
        self.y_label.setObjectName("y_label")
        self.ySize_horizontalLayout.addWidget(self.y_label)
        self.sizeY_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.size_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizeY_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.sizeY_doubleSpinBox.setSizePolicy(sizePolicy)
        self.sizeY_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sizeY_doubleSpinBox.setFrame(True)
        self.sizeY_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sizeY_doubleSpinBox.setDecimals(1)
        self.sizeY_doubleSpinBox.setMinimum(0.1)
        self.sizeY_doubleSpinBox.setMaximum(10.0)
        self.sizeY_doubleSpinBox.setSingleStep(0.1)
        self.sizeY_doubleSpinBox.setProperty("value", 1.0)
        self.sizeY_doubleSpinBox.setObjectName("sizeY_doubleSpinBox")
        self.ySize_horizontalLayout.addWidget(self.sizeY_doubleSpinBox)
        self.verticalLayout_4.addLayout(self.ySize_horizontalLayout)
        self.verticalLayout_2.addWidget(self.size_groupBox)
        self.opacity_groupBox = QtWidgets.QGroupBox(self.tools_verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opacity_groupBox.sizePolicy().hasHeightForWidth())
        self.opacity_groupBox.setSizePolicy(sizePolicy)
        self.opacity_groupBox.setObjectName("opacity_groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.opacity_groupBox)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setContentsMargins(3, 6, 3, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.opacity_label = QtWidgets.QLabel(self.opacity_groupBox)
        self.opacity_label.setText("")
        self.opacity_label.setObjectName("opacity_label")
        self.verticalLayout_5.addWidget(self.opacity_label)
        self.opacity_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.opacity_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opacity_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.opacity_doubleSpinBox.setSizePolicy(sizePolicy)
        self.opacity_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.opacity_doubleSpinBox.setMaximum(1.0)
        self.opacity_doubleSpinBox.setSingleStep(0.1)
        self.opacity_doubleSpinBox.setProperty("value", 1.0)
        self.opacity_doubleSpinBox.setObjectName("opacity_doubleSpinBox")
        self.verticalLayout_5.addWidget(self.opacity_doubleSpinBox)
        self.verticalLayout_2.addWidget(self.opacity_groupBox)
        self.color_groupBox = QtWidgets.QGroupBox(self.tools_verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_groupBox.sizePolicy().hasHeightForWidth())
        self.color_groupBox.setSizePolicy(sizePolicy)
        self.color_groupBox.setObjectName("color_groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.color_groupBox)
        self.verticalLayout_6.setContentsMargins(18, 2, 18, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.color_pushButton = QtWidgets.QPushButton(self.color_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_pushButton.sizePolicy().hasHeightForWidth())
        self.color_pushButton.setSizePolicy(sizePolicy)
        self.color_pushButton.setMouseTracking(False)
        self.color_pushButton.setText("")
        self.color_pushButton.setCheckable(False)
        self.color_pushButton.setFlat(False)
        self.color_pushButton.setObjectName("color_pushButton")
        self.verticalLayout_6.addWidget(self.color_pushButton)
        self.verticalLayout_2.addWidget(self.color_groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.main_splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.main_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.main_verticalLayout.setSpacing(0)
        self.main_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.main_verticalLayout.setObjectName("main_verticalLayout")
        self.main_tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.main_tabWidget.setCursor(QtCore.Qt.ArrowCursor)
        self.main_tabWidget.setMouseTracking(False)
        self.main_tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.main_tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main_tabWidget.setUsesScrollButtons(True)
        self.main_tabWidget.setDocumentMode(False)
        self.main_tabWidget.setTabsClosable(True)
        self.main_tabWidget.setMovable(True)
        self.main_tabWidget.setObjectName("main_tabWidget")
        self.default_tab = QtWidgets.QWidget()
        self.default_tab.setObjectName("default_tab")
        self.main_tabWidget.addTab(self.default_tab, "")
        self.main_verticalLayout.addWidget(self.main_tabWidget)
        self.verticalLayout_3.addWidget(self.main_splitter)
        nuPicker_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(nuPicker_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 535, 21))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.edit_menu = QtWidgets.QMenu(self.menubar)
        self.edit_menu.setObjectName("edit_menu")
        self.setBackground_menu = QtWidgets.QMenu(self.edit_menu)
        self.setBackground_menu.setObjectName("setBackground_menu")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.dockWindow_action = QtWidgets.QMenu(self.menuWindow)
        self.dockWindow_action.setObjectName("dockWindow_action")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        nuPicker_MainWindow.setMenuBar(self.menubar)
        self.open_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.open_action.setObjectName("open_action")
        self.save_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.save_action.setObjectName("save_action")
        self.saveAs_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.saveAs_action.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.saveAs_action.setObjectName("saveAs_action")
        self.newTab_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.newTab_action.setEnabled(True)
        self.newTab_action.setObjectName("newTab_action")
        self.quit_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.quit_action.setObjectName("quit_action")
        self.toLeft_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.toLeft_action.setObjectName("toLeft_action")
        self.toRight_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.toRight_action.setObjectName("toRight_action")
        self.constrainProportions_aciton = QtWidgets.QAction(nuPicker_MainWindow)
        self.constrainProportions_aciton.setCheckable(True)
        self.constrainProportions_aciton.setChecked(True)
        self.constrainProportions_aciton.setObjectName("constrainProportions_aciton")
        self.enableScrollRoll_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.enableScrollRoll_action.setCheckable(True)
        self.enableScrollRoll_action.setObjectName("enableScrollRoll_action")
        self.frameSelected_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.frameSelected_action.setObjectName("frameSelected_action")
        self.undo_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.undo_action.setObjectName("undo_action")
        self.redo_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.redo_action.setObjectName("redo_action")
        self.browseBackground_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.browseBackground_action.setObjectName("browseBackground_action")
        self.setDefaultBackground_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.setDefaultBackground_action.setObjectName("setDefaultBackground_action")
        self.newButton_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.newButton_action.setObjectName("newButton_action")
        self.deleteButton_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.deleteButton_action.setObjectName("deleteButton_action")
        self.setDirectory_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.setDirectory_action.setObjectName("setDirectory_action")
        self.newCmdButton_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.newCmdButton_action.setObjectName("newCmdButton_action")
        self.alignLeft_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.alignLeft_action.setObjectName("alignLeft_action")
        self.alignTop_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.alignTop_action.setObjectName("alignTop_action")
        self.alignRight_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.alignRight_action.setObjectName("alignRight_action")
        self.alignBottom_action = QtWidgets.QAction(nuPicker_MainWindow)
        self.alignBottom_action.setObjectName("alignBottom_action")
        self.file_menu.addAction(self.open_action)
        self.file_menu.addAction(self.save_action)
        self.file_menu.addAction(self.saveAs_action)
        self.file_menu.addAction(self.setDirectory_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.quit_action)
        self.setBackground_menu.addAction(self.browseBackground_action)
        self.setBackground_menu.addAction(self.setDefaultBackground_action)
        self.edit_menu.addAction(self.undo_action)
        self.edit_menu.addAction(self.redo_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.newButton_action)
        self.edit_menu.addAction(self.newCmdButton_action)
        self.edit_menu.addAction(self.deleteButton_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.alignLeft_action)
        self.edit_menu.addAction(self.alignRight_action)
        self.edit_menu.addAction(self.alignTop_action)
        self.edit_menu.addAction(self.alignBottom_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.newTab_action)
        self.edit_menu.addAction(self.setBackground_menu.menuAction())
        self.dockWindow_action.addAction(self.toLeft_action)
        self.dockWindow_action.addAction(self.toRight_action)
        self.menuWindow.addAction(self.dockWindow_action.menuAction())
        self.menuWindow.addAction(self.frameSelected_action)
        self.menuSettings.addAction(self.constrainProportions_aciton)
        self.menuSettings.addAction(self.enableScrollRoll_action)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.edit_menu.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(nuPicker_MainWindow)
        self.main_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(nuPicker_MainWindow)

    def retranslateUi(self, nuPicker_MainWindow):
        nuPicker_MainWindow.setWindowTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "MainWindow", None, -1))
        self.namespace_label.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "namespace", None, -1))
        self.label_groupBox.setTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "label", None, -1))
        self.size_groupBox.setTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "size", None, -1))
        self.x_label.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "X", None, -1))
        self.y_label.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Y", None, -1))
        self.opacity_groupBox.setTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "opacity", None, -1))
        self.color_groupBox.setTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "color", None, -1))
        self.color_pushButton.setToolTip(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Hold to use this color", None, -1))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.default_tab), QtWidgets.QApplication.translate("nuPicker_MainWindow", "default", None, -1))
        self.file_menu.setTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "File", None, -1))
        self.edit_menu.setTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Edit", None, -1))
        self.setBackground_menu.setTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Set background...", None, -1))
        self.menuWindow.setTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "View", None, -1))
        self.dockWindow_action.setTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Dock window", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Settings", None, -1))
        self.open_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Open", None, -1))
        self.open_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+O", None, -1))
        self.save_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Save", None, -1))
        self.save_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+S", None, -1))
        self.saveAs_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Save as...", None, -1))
        self.saveAs_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+Shift+S", None, -1))
        self.newTab_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "New tab", None, -1))
        self.newTab_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+N", None, -1))
        self.quit_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Quit", None, -1))
        self.toLeft_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "To left", None, -1))
        self.toRight_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "To Right", None, -1))
        self.constrainProportions_aciton.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Constrain proportions", None, -1))
        self.enableScrollRoll_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Enable scroll roll", None, -1))
        self.frameSelected_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Frame selected", None, -1))
        self.frameSelected_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "F", None, -1))
        self.undo_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Undo", None, -1))
        self.undo_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+Z", None, -1))
        self.redo_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Redo", None, -1))
        self.redo_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Shift+Z", None, -1))
        self.browseBackground_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Browse...", None, -1))
        self.setDefaultBackground_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Set to default", None, -1))
        self.newButton_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "New button", None, -1))
        self.newButton_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+G", None, -1))
        self.deleteButton_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Delete button", None, -1))
        self.deleteButton_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Backspace", None, -1))
        self.setDirectory_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Set directory...", None, -1))
        self.newCmdButton_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "New cmd button", None, -1))
        self.newCmdButton_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+Shift+G", None, -1))
        self.alignLeft_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Align left", None, -1))
        self.alignLeft_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+Left", None, -1))
        self.alignTop_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Align top", None, -1))
        self.alignTop_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+Up", None, -1))
        self.alignRight_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Align right", None, -1))
        self.alignRight_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+Right", None, -1))
        self.alignBottom_action.setText(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Align bottom", None, -1))
        self.alignBottom_action.setShortcut(QtWidgets.QApplication.translate("nuPicker_MainWindow", "Ctrl+Down", None, -1))

